spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update         # hızlı başlangıç için; prod'da kapatıp Flyway kullan
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC    # OffsetDateTime/Instant için tavsiye

